s|  FILE_EMISSIONSCENARIO.*|  FILE_EMISSIONSCENARIO =  "REMIND_SSP2-PkBudg1100",|g
s|  RUNNAME.*|  RUNNAME =  "SSP2-PkBudg1100",|g
s|  RUNDATE.*|  RUNDATE =  "03/12/20",|g
s|  RF_SOLAR_SCALE =.*|  RF_SOLAR_SCALE =  0,|g
